movierecommendation/movierecommendation/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^movies/', include('movies.urls', namespace="movies")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace="auth")),
    
]

movierecommendation/movies/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /
    url(r'^$', views.review_list, name='review_list'),
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    url(r'^movie$', views.movie_list, name='movie_list'),
    url(r'^movie/(?P<movie_id>[0-9]+)/$', views.movie_detail, name='movie_detail'),
    url(r'^movie/(?P<movie_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^movie/user/(?P<username>\w+)/$', views.user_review_list, name='user_review_list'),
    url(r'^movie/user/$', views.user_review_list, name='user_review_list'),
    url(r'^recommendation/$', views.user_recommendation_list, name='user_recommendation_list'),
    
]

movierecommendation/movies/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
import numpy as np


class Movie(models.Model):
    name = models.CharField(max_length=200)
    genre = models.CharField(max_length=200)

    def average_rating(self):
        all_ratings = map(lambda x: x.rating, self.review_set.all())
        return np.mean(all_ratings)
        
    def __unicode__(self):
        return self.name


class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    movie = models.ForeignKey(Movie)
    pub_date = models.DateTimeField('date published')
    user_name = models.CharField(max_length=100)  
    rating = models.IntegerField(choices=RATING_CHOICES)

class Cluster(models.Model):
    name = models.CharField(max_length=100)
    users = models.ManyToManyField(User)

    def get_members(self):
        return "\n".join([u.username for u in self.users.all()])

movierecommendation/movies/forms.py
from django.forms import ModelForm, Textarea
from movies.models import Review


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating']

movierecommendation/movies/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Review, Movie
from .forms import ReviewForm
from django.core.paginator import Paginator
import datetime

from django.contrib.auth.decorators import login_required


def review_list(request):
    latest_review_list = Review.objects.order_by('-pub_date').all()
    page = request.GET.get('page', 1)
    paginator = Paginator(latest_review_list, 252)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
    context = {'latest_review_list':queryset}
    return render(request, 'movies/review_list.html', context)


def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'movies/review_detail.html', {'review': review})


def movie_list(request):
    for x in Review.objects.all().iterator(): x.delete()     
    movie_list = Movie.objects.order_by('-name').all()
    page = request.GET.get('page', 1)
    paginator = Paginator(movie_list, 84)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
    context = {'movie_list':queryset}
    return render(request, 'movies/movie_list.html', context)


def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movies/movie_detail.html', {'movie': movie})


@login_required
def add_review(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    if request.POST:
        form = ReviewForm(request.POST)
    else:
        form = ReviewForm()  
    if form.is_valid():
        user_name = request.user.username
        review = form.save(commit=False) # commit = False means that this instantiate but not save a Review model object
        review.movie = movie
        review.user_name = user_name # Why use this instead of a ForeignKey to user?
        review.pub_date = datetime.datetime.now() # works as long as pub_date is a DateTimeField
        review.save() # save to the DB now
        return HttpResponseRedirect(reverse('movies:movie_detail', args=(movie.id,))) # THIS will redirect only upon form save
    return render(request, 'movies/movie_detail.html', {'movie': movie, 'form': form})


def user_review_list(request, username=None):
    if not username:
        username = request.user.username
    latest_review_list = Review.objects.filter(user_name=username).order_by('-pub_date')
    context = {'latest_review_list':latest_review_list, 'username':username}
    return render(request, 'movies/user_review_list.html', context)


@login_required
def user_recommendation_list(request):
    return 0

movierecommendation/movies/templates/movies/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'movies:review_list' %}">YouMDB</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'movies:movie_list' %}">Movie list</a></li>
                <li><a href="{% url 'movies:review_list' %}">Home</a></li>
            </ul>
              <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'movies:user_review_list' user.username %}">Hello {{ user.username }}</a></li>
                <li><a href="{% url 'movies:user_recommendation_list' %}">Movie suggestions</a></li>
                <li><a href="{% url 'auth:logout' %}?next=/movies"">Logout</a></li>
                {% else %}
                <li><a href="{% url 'auth:login' %}">Login</a></li>
                <li><a href="/accounts/register">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    

    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}

movierecommendation/movies/templates/movies/movie_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
<h2>{{ movie.name }}</h2>
<h5>{{ movie.review_set.count }} reviews ({{ movie.average_rating | floatformat }} average rating)</h5>
{% endblock %}

{% block content %}
<h3>Recent reviews</h3>

{% if movie.review_set.all %}
<div class="row">
    {% for review in movie.review_set.all %}
    <div class="col-xs-6 col-lg-4">
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by <a>{{ review.user_name }}</a></h6>
        <h5><a href="{% url 'movies:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No reviews for this movie yet</p>
{% endif %}

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'movies:add_review' movie.id %}" method="post" class="form">
      {% csrf_token %}
     {% for field in form %}
    {% bootstrap_field field %}
  {% endfor %}   
 {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Add
    </button>
    {% endbuttons %}
</form>
{% endblock %}

movierecommendation/movies/templates/movies/movie_list.html
{% extends 'base.html' %}

{% block title %}
<h2>Movie list</h2>
{% endblock %}

{% block content %}
{% if movie_list %}
<div class="row">
    {% for movie in movie_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'movies:movie_detail' movie.id %}">
        {{ movie.name }}
        </a></h4>
        <h5>{{ movie.review_set.count }} reviews</h5>
        <h5>{{ movie.average_rating | floatformat }} average rating</h5>
    </div>
    {% endfor %}
    {% if movie_list.has_other_pages %}

  <ul class="pagination">
    {% if movie_list.has_previous %}
      <li><a href="?page={{ movie_list.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in movie_list.paginator.page_range %}
      {% if movie_list.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if movie_list.has_next %}
      <li><a href="?page={{ movie_list.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</div>
{% else %}
    <p>No movies are available.</p>

{% endif %}
{% endblock %}

movierecommendation/movies/templates/movies/review_detail.html
{% extends 'base.html' %}

{% block title %}
<h2><a href="{% url 'movies:review_detail' review.id %}">{{ review.movie.name }}</a></h2>
{% endblock %}

{% block content %}
<h4>Rated {{ review.rating }} of 5 by <a >{{ review.user_name }}</a></h4>
<p>{{ review.pub_date }}</p>
{% endblock %}

movierecommendation/movies/templates/movies/review_list.html
{% extends 'base.html' %}

{% block title %}
<h2>Latest reviews</h2>
{% endblock %}

{% block content %}
{% if latest_review_list %}
<div class="row">
    {% for review in latest_review_list %}
    <div class="col-xs-6 col-lg-4">
        <h4> <a href="{% url 'movies:review_detail' review.id %}" >
        {{ review.movie.name }}
        </a></h4>
        <h6>Rated {{ review.rating }} of 5 by {{ review.id }}</h6>
    </div>
    {% endfor %}
</div>


{% if latest_review_list.has_other_pages %}
  <ul class="pagination">
    {% if latest_review_list.has_previous %}
      <li><a href="?page={{ latest_review_list.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in latest_review_list.paginator.page_range %}
      {% if latest_review_list.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if latest_review_list.has_next %}
      <li><a href="?page={{ latest_review_list.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% else %}
<p>No reviews are available.</p>
{% endif %}
{% endblock %}

movierecommendation/movies/templates/movies/user_recommendation_list.html
{% extends 'movies/movie_list.html' %}

{% block title %}
<h2>Movie suggestions for {{ username }}</h2>
{% endblock %}

movierecommendation/movies/templates/movies/user_review_list.html
{% extends 'movies/review_list.html' %}

{% block title %}
<h2>Reviews by {{ username }}</h2>
{% endblock %}

movierecommendation/templates/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'movies:review_list' %}">YouMDB</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'movies:movie_list' %}">Movie list</a></li>
                <li><a href="{% url 'movies:review_list' %}">Home</a></li>
            </ul>
              <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'movies:user_review_list' user.username %}">Hello {{ user.username }}</a></li>
                <li><a href="{% url 'movies:user_recommendation_list' %}">Movie suggestions</a></li>
                <li><a href="{% url 'auth:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'auth:login' %}">Login</a></li>
                <li><a href="/accounts/register">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    

    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}